In [2]:
import numpy as np

In [3]:
myList = [1,2,3]
type(myList)

list

In [4]:
myArray = np.array(myList)
type(myArray)

numpy.ndarray

In [6]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [7]:
np.zeros(shape=(5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np.ones(shape=(2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.random.seed(101)
arr = np.random.randint(0,100,10)
print(arr)

[95 11 81 70 63 87 75  9 77 40]


In [11]:
arr2 = np.random.randint(0,100,10)
print(arr2)

[ 4 63 40 60 92 64  5 12 93 40]


In [12]:
arr2.max()

93

In [13]:
arr2.argmax() # returns the location of the max value

8

In [14]:
arr.min()
arr.argmin()

7

In [15]:
arr.shape

(10,)

In [16]:
arr2.shape

(10,)

In [18]:
arr.reshape((5,2)) #reshape into the 5 2 order

array([[95, 11],
       [81, 70],
       [63, 87],
       [75,  9],
       [77, 40]])

In [20]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [21]:
row = 0
col = 1
mat[row, col] # getting the second column of the first row element

1

In [22]:
mat[:,1] # get element of column 1

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [24]:
mat[:,1].reshape(10,1)

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [25]:
mat[1,:] # get everything from the second row

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [26]:
mat[0:3,0:3] # get rows till 3 and column til 3 

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [28]:
mat[:,-1].reshape(10,1)

array([[ 9],
       [19],
       [29],
       [39],
       [49],
       [59],
       [69],
       [79],
       [89],
       [99]])

In [29]:
mat[:,-2] = 0 # set the second last column to 0

In [30]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  0,  9],
       [10, 11, 12, 13, 14, 15, 16, 17,  0, 19],
       [20, 21, 22, 23, 24, 25, 26, 27,  0, 29],
       [30, 31, 32, 33, 34, 35, 36, 37,  0, 39],
       [40, 41, 42, 43, 44, 45, 46, 47,  0, 49],
       [50, 51, 52, 53, 54, 55, 56, 57,  0, 59],
       [60, 61, 62, 63, 64, 65, 66, 67,  0, 69],
       [70, 71, 72, 73, 74, 75, 76, 77,  0, 79],
       [80, 81, 82, 83, 84, 85, 86, 87,  0, 89],
       [90, 91, 92, 93, 94, 95, 96, 97,  0, 99]])