In [1]:
import numpy as np
from numpy import genfromtxt

In [7]:
data = genfromtxt('data_banknote_authentication.txt',delimiter=',')

In [8]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [9]:
data.shape

(1372, 5)

In [10]:
labels = data[:,4]

In [12]:
features = data[:,0:4]

In [14]:
# splitting the data into train and test
X = features
y = labels

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.33,random_state=42)

In [20]:
from sklearn.preprocessing import MinMaxScaler

In [22]:
scaler = MinMaxScaler()

In [23]:
scaler.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [24]:
scaled_X_train = scaler.transform(X_train)

In [26]:
# fit only train data -> data leaking
scaled_X_test = scaler.transform(X_test)

In [29]:
from keras.models import Sequential
from keras.layers import Dense

In [31]:
model = Sequential()

# adding layers
model.add(Dense(4,input_dim=4,activation='relu'))

model.add(Dense(8,activation='relu'))

model.add(Dense(1,activation='sigmoid'))

In [32]:
model.compile(loss = 'binary_crossentropy',optimizer='adam', metrics=['accuracy'])

In [33]:
model.fit(scaled_X_train,y_train,epochs=50,verbose=2)

Epoch 1/50
 - 0s - loss: 0.6767 - acc: 0.5495
Epoch 2/50
 - 0s - loss: 0.6616 - acc: 0.5495
Epoch 3/50
 - 0s - loss: 0.6480 - acc: 0.5495
Epoch 4/50
 - 0s - loss: 0.6313 - acc: 0.5495
Epoch 5/50
 - 0s - loss: 0.6152 - acc: 0.5495
Epoch 6/50
 - 0s - loss: 0.6037 - acc: 0.5495
Epoch 7/50
 - 0s - loss: 0.5926 - acc: 0.5495
Epoch 8/50
 - 0s - loss: 0.5810 - acc: 0.5647
Epoch 9/50
 - 0s - loss: 0.5688 - acc: 0.6344
Epoch 10/50
 - 0s - loss: 0.5562 - acc: 0.7356
Epoch 11/50
 - 0s - loss: 0.5426 - acc: 0.7476
Epoch 12/50
 - 0s - loss: 0.5285 - acc: 0.7726
Epoch 13/50
 - 0s - loss: 0.5142 - acc: 0.7965
Epoch 14/50
 - 0s - loss: 0.4991 - acc: 0.8041
Epoch 15/50
 - 0s - loss: 0.4840 - acc: 0.8215
Epoch 16/50
 - 0s - loss: 0.4689 - acc: 0.8411
Epoch 17/50
 - 0s - loss: 0.4537 - acc: 0.8444
Epoch 18/50
 - 0s - loss: 0.4389 - acc: 0.8498
Epoch 19/50
 - 0s - loss: 0.4247 - acc: 0.8847
Epoch 20/50
 - 0s - loss: 0.4107 - acc: 0.8879
Epoch 21/50
 - 0s - loss: 0.3977 - acc: 0.8934
Epoch 22/50
 - 0s - lo

In [38]:
# on test data
# model.predict_classes(scaled_X_test)

In [35]:
model.metrics_names

['loss', 'acc']

In [40]:
# evaluating the model performance
from sklearn.metrics import confusion_matrix,classification_report

In [41]:
predictions = model.predict_classes(scaled_X_test)

In [42]:
confusion_matrix(y_test,predictions)

array([[254,   3],
       [ 15, 181]], dtype=int64)

In [43]:
print(classification_report(y_test,predictions))

             precision    recall  f1-score   support

        0.0       0.94      0.99      0.97       257
        1.0       0.98      0.92      0.95       196

avg / total       0.96      0.96      0.96       453



In [44]:
model.save('my_model.h5')

In [45]:
from keras.models import load_model

In [47]:
my_model = load_model('my_model.h5')

In [48]:
# my_model.predict_classes(scaled_X_test)

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
    